version: '3'

services:
    app:
        image: erikzogg/text-in-model-out-app
        container_name: text-in-model-out-app
        hostname: app
        volumes:
            - .:/usr/src/app
        command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
        expose:
            - 8000

    nginx:
        image: erikzogg/text-in-model-out-nginx
        container_name: text-in-model-out-nginx
        hostname: nginx
        volumes:
            - ./static:/static
        depends_on:
            - app
        ports:
            - '80:80'
