name: Build Docker Image

on:
    push:
        branches: main

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Docker Setup QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Docker Setup Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Docker Login
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build and push Docker image 1
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./Dockerfile
                    platforms: linux/amd64
                    push: true
                    tags: |
                        erikzogg/text-in-model-out-app:latest

            -   name: Build and push Docker image 2
                uses: docker/build-push-action@v2
                with:
                    context: .docker/nginx
                    file: ./Dockerfile
                    platforms: linux/amd64
                    push: true
                    tags: |
                        erikzogg/text-in-model-out-nginx:latest
